package com.ivieleague.kbuild.intellij

import com.ivieleague.kbuild.common.Library
import org.redundent.kotlin.xml.xml
import java.io.File
import java.net.URLClassLoader

/**
 * Generates IDE support files for editing Build.kt scripts.
 *
 * Creates a lightweight IntelliJ project (no Gradle) in `.kbuild/ide/` that:
 * - References the Build.kt file from the project root
 * - Includes kbuild's libraries for autocomplete/navigation
 * - Can be opened directly in IntelliJ
 *
 * Usage:
 * ```
 * kbuild --ide                    # Generate IDE files and open IntelliJ
 * # Build.kt will have full autocomplete for kbuild APIs
 * ```
 */
object BuildScriptIdeBuild {

    // kbuild version for Maven coordinates
    const val KBUILD_VERSION = "1.0-SNAPSHOT"

    // Key dependencies that Build.kt files need
    val KBUILD_DEPENDENCIES = listOf(
        "com.ivieleague:kbuild:$KBUILD_VERSION",
        "com.lightningkite:reactive-jvm:6.0.0-prerelease-26",
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    )

    /**
     * Generate IDE support files for Build.kt.
     *
     * @param projectRoot The project root containing Build.kt
     * @param buildFileName The name of the build file (default: "Build.kt")
     * @return The IDE project directory (.kbuild/ide)
     */
    fun generate(
        projectRoot: File,
        buildFileName: String = "Build.kt"
    ): File {
        val ideDir = projectRoot.resolve(".kbuild/ide")
        ideDir.deleteRecursively()
        ideDir.mkdirs()

        // Get kbuild's classpath and convert to Library objects
        val libraries = getKBuildLibraries()

        // Find all *Build.kt files in the project root
        val buildFiles = projectRoot.listFiles { file ->
            file.isFile && file.name.endsWith("Build.kt")
        }?.toList() ?: emptyList()

        // Generate annotation stubs file in project root (for Skate compatibility)
        generateAnnotationStubs(projectRoot)

        // Create the IntelliJ project structure
        createIntelliJProject(ideDir, projectRoot, buildFiles, libraries)

        return ideDir
    }

    /**
     * Generate annotation stubs file that defines @DependsOn, @Repository, etc.
     * This allows tools like Skate to work with Build.kt files.
     */
    private fun generateAnnotationStubs(projectRoot: File) {
        val stubsFile = projectRoot.resolve("KBuildAnnotations.kt")
        stubsFile.writeText(buildString {
            appendLine("// Generated by kbuild --ide")
            appendLine("// These annotations allow Build.kt to be used with tools like Skate")
            appendLine()
            appendLine("@Retention(AnnotationRetention.SOURCE)")
            appendLine("@Target(AnnotationTarget.FILE)")
            appendLine("@Repeatable")
            appendLine("annotation class Repository(val url: String)")
            appendLine()
            appendLine("@Retention(AnnotationRetention.SOURCE)")
            appendLine("@Target(AnnotationTarget.FILE)")
            appendLine("@Repeatable")
            appendLine("annotation class DependsOn(val maven: String)")
            appendLine()
            appendLine("@Retention(AnnotationRetention.SOURCE)")
            appendLine("@Target(AnnotationTarget.FILE)")
            appendLine("@Repeatable")
            appendLine("annotation class Import(val file: String)")
        })

        // Also update Build.kt files to include the @file:DependsOn annotations if not present
        val buildFiles = projectRoot.listFiles { file ->
            file.isFile && file.name.endsWith("Build.kt")
        } ?: emptyArray()

        for (buildFile in buildFiles) {
            addDependsOnAnnotations(buildFile)
        }
    }

    /**
     * Add @file:DependsOn annotations to a Build.kt file if not already present.
     */
    private fun addDependsOnAnnotations(buildFile: File) {
        val content = buildFile.readText()

        // Check if annotations already exist
        if (content.contains("@file:DependsOn")) {
            return // Already has annotations
        }

        // Build the annotation block
        val annotationBlock = buildString {
            appendLine("// KBuild dependencies (for Skate compatibility)")
            appendLine("@file:Repository(\"https://lightningkite-maven.s3.us-west-2.amazonaws.com\")")
            for (dep in KBUILD_DEPENDENCIES) {
                appendLine("@file:DependsOn(\"$dep\")")
            }
            appendLine()
        }

        // Insert at the beginning of the file (before package or first import)
        val newContent = annotationBlock + content
        buildFile.writeText(newContent)
    }

    /**
     * Create IntelliJ project files.
     */
    private fun createIntelliJProject(
        ideDir: File,
        projectRoot: File,
        sourceFiles: List<File>,
        libraries: List<Library>
    ) {
        // Create src folder with symlinks to Build.kt files
        val srcDir = ideDir.resolve("src")
        srcDir.mkdirs()

        for (sourceFile in sourceFiles) {
            val linkFile = srcDir.resolve(sourceFile.name)
            try {
                java.nio.file.Files.createSymbolicLink(
                    linkFile.toPath(),
                    sourceFile.toPath()
                )
            } catch (e: Exception) {
                // Fallback to copy if symlink fails
                sourceFile.copyTo(linkFile, overwrite = true)
            }
        }

        // Also symlink the annotation stubs file
        val stubsFile = projectRoot.resolve("KBuildAnnotations.kt")
        if (stubsFile.exists()) {
            val linkFile = srcDir.resolve(stubsFile.name)
            try {
                java.nio.file.Files.createSymbolicLink(
                    linkFile.toPath(),
                    stubsFile.toPath()
                )
            } catch (e: Exception) {
                stubsFile.copyTo(linkFile, overwrite = true)
            }
        }

        // Create .idea folder
        val ideaDir = ideDir.resolve(".idea")
        ideaDir.mkdirs()

        // Generate project files
        val moduleFile = ideDir.resolve("kbuild-script.iml")
        moduleFile.writeText(generateModuleFile(ideDir, listOf(srcDir), libraries))

        ideaDir.resolve("modules.xml").writeText(generateModulesFile(ideDir, listOf(moduleFile)))
        ideaDir.resolve("misc.xml").writeText(generateMiscFile(ideDir))
        ideaDir.resolve("kotlinc.xml").writeText(generateKotlincFile())

        // Create library files
        val libDir = ideaDir.resolve("libraries")
        libDir.mkdirs()

        for (lib in libraries) {
            val libFile = libDir.resolve(lib.fileSafeName + ".xml")
            libFile.writeText(generateLibraryFile(lib))
        }
    }

    /**
     * Generate the .iml module file.
     */
    private fun generateModuleFile(
        projectRoot: File,
        sourceDirectories: List<File>,
        libraries: List<Library>
    ): String {
        return xml("module") {
            includeXmlProlog = true
            attribute("type", "JAVA_MODULE")
            attribute("version", "4")

            "component"("name" to "NewModuleRootManager", "inherit-compiler-output" to "true") {
                "exclude-output"()

                "content"("url" to "file://${projectRoot.absolutePath}") {
                    for (src in sourceDirectories) {
                        "sourceFolder"(
                            "url" to "file://${src.absolutePath}",
                            "isTestSource" to "false"
                        )
                    }
                }

                "orderEntry"("type" to "inheritedJdk")
                "orderEntry"("type" to "sourceFolder", "forTests" to "false")

                for (lib in libraries) {
                    "orderEntry"(
                        "type" to "library",
                        "level" to "project",
                        "name" to lib.fileSafeName
                    )
                }
            }
        }.toString(prettyFormat = true)
    }

    /**
     * Generate modules.xml.
     */
    private fun generateModulesFile(projectRoot: File, modules: List<File>): String {
        return xml("project") {
            includeXmlProlog = true
            attribute("version", "4")

            "component"("name" to "ProjectModuleManager") {
                "modules" {
                    for (module in modules) {
                        "module"(
                            "fileurl" to "file://${module.absolutePath}",
                            "filepath" to module.absolutePath
                        )
                    }
                }
            }
        }.toString(prettyFormat = true)
    }

    /**
     * Generate misc.xml.
     */
    private fun generateMiscFile(projectRoot: File): String {
        return xml("project") {
            includeXmlProlog = true
            attribute("version", "4")

            "component"(
                "name" to "ProjectRootManager",
                "version" to "2",
                "languageLevel" to "JDK_17",
                "default" to "true",
                "project-jdk-name" to "17",
                "project-jdk-type" to "JavaSDK"
            ) {
                "output"("url" to "file://${projectRoot.absolutePath}/out")
            }
        }.toString(prettyFormat = true)
    }

    /**
     * Generate kotlinc.xml with Kotlin compiler settings.
     */
    private fun generateKotlincFile(): String {
        return xml("project") {
            includeXmlProlog = true
            attribute("version", "4")

            "component"("name" to "Kotlin2JvmCompilerArguments") {
                "option"("name" to "jvmTarget", "value" to "17")
            }
            "component"("name" to "KotlinCommonCompilerArguments") {
                "option"("name" to "apiVersion", "value" to "2.2")
                "option"("name" to "languageVersion", "value" to "2.2")
            }
        }.toString(prettyFormat = true)
    }

    /**
     * Generate a library XML file.
     */
    private fun generateLibraryFile(library: Library): String {
        return xml("component") {
            attribute("name", "libraryTable")

            "library"("name" to library.fileSafeName) {
                "CLASSES" {
                    "root"("url" to "jar://${library.default.absolutePath}!/")
                }
                "JAVADOC" {
                    library.documentation?.let {
                        "root"("url" to "jar://${it.absolutePath}!/")
                    }
                }
                "SOURCES" {
                    library.sources?.let {
                        "root"("url" to "jar://${it.absolutePath}!/")
                    }
                }
            }
        }.toString(prettyFormat = true)
    }

    /**
     * Get kbuild's runtime libraries.
     */
    private fun getKBuildLibraries(): List<Library> {
        val classpath = getKBuildClasspath()
        return classpath
            .filter { it.extension == "jar" }
            .map { jar ->
                Library(
                    name = jar.nameWithoutExtension,
                    default = jar,
                    sources = null,
                    documentation = null
                )
            }
    }

    /**
     * Get kbuild's runtime classpath.
     */
    private fun getKBuildClasspath(): Set<File> {
        val classpath = mutableSetOf<File>()

        // Try system property first
        System.getProperty("kbuild.classpath")?.let { cp ->
            cp.split(File.pathSeparator).forEach { path ->
                val file = File(path)
                if (file.exists()) {
                    classpath.add(file)
                }
            }
        }

        // Try URLClassLoader
        val classLoader = this::class.java.classLoader
        if (classLoader is URLClassLoader) {
            classLoader.urLs.forEach { url ->
                if (url.protocol == "file") {
                    classpath.add(File(url.toURI()))
                }
            }
        }

        // Fallback: java.class.path
        if (classpath.isEmpty()) {
            System.getProperty("java.class.path")?.split(File.pathSeparator)?.forEach { path ->
                val file = File(path)
                if (file.exists()) {
                    classpath.add(file)
                }
            }
        }

        return classpath
    }
}
