package com.ivieleague.kbuild.intellij

import com.ivieleague.kbuild.common.DependencyScope
import com.ivieleague.kbuild.kmp.*
import com.ivieleague.kbuild.kotlin.Kotlin
import java.io.File

/**
 * Generates minimal Gradle build files for IntelliJ IDE integration.
 *
 * These files are for IDE purposes only - they provide:
 * - Source set structure for code navigation
 * - Dependency information for autocomplete
 * - expect/actual resolution for KMP projects
 *
 * The actual build is still performed by KBuild.
 *
 * Usage:
 * ```kotlin
 * val config = KmpProjectConfig(...)
 * GradleIdeBuild.generate(config)
 * // Then: IntelliJ -> Open -> select the project folder -> Import as Gradle project
 * ```
 */
object GradleIdeBuild {

    val KOTLIN_VERSION = Kotlin.versionString
    const val IDE_ONLY_COMMENT = """
// ============================================================================
// IDE-ONLY BUILD FILE - Generated by KBuild
// ============================================================================
// This file exists solely for IntelliJ IDEA integration (autocomplete,
// navigation, expect/actual resolution). DO NOT use this for building.
//
// To build the project, use KBuild directly.
// ============================================================================
"""

    /**
     * Generate Gradle files for a KMP project.
     *
     * Creates:
     * - settings.gradle.kts
     * - build.gradle.kts
     * - gradle.properties
     * - gradle/libs.versions.toml (optional, for version catalog)
     *
     * @param config The KMP project configuration
     * @param outputDir Where to write the Gradle files (defaults to project root)
     * @return The project root directory
     */
    fun generate(
        config: KmpProjectConfig,
        outputDir: File = config.projectRoot
    ): File {
        generateSettingsGradle(config, outputDir)
        generateBuildGradle(config, outputDir)
        generateGradleProperties(outputDir)
        generateGradleWrapper(outputDir)
        return outputDir
    }

    /**
     * Generate Gradle files for multiple KMP projects (monorepo).
     *
     * @param rootDir The monorepo root directory
     * @param projectName The root project name
     * @param modules Map of module path to KmpProjectConfig
     * @return The root directory
     */
    fun generateMultiModule(
        rootDir: File,
        projectName: String,
        modules: Map<String, KmpProjectConfig>
    ): File {
        generateRootSettingsGradle(rootDir, projectName, modules.keys)
        generateRootBuildGradle(rootDir)
        generateGradleProperties(rootDir)
        generateGradleWrapper(rootDir)

        for ((path, config) in modules) {
            val moduleDir = rootDir.resolve(path)
            generateBuildGradle(config, moduleDir)
        }

        return rootDir
    }

    private fun generateSettingsGradle(config: KmpProjectConfig, outputDir: File) {
        outputDir.resolve("settings.gradle.kts").writeText(buildString {
            appendLine(IDE_ONLY_COMMENT.trimIndent())
            appendLine()
            appendLine("rootProject.name = \"${config.name}\"")
            appendLine()
            appendLine("pluginManagement {")
            appendLine("    repositories {")
            appendLine("        gradlePluginPortal()")
            appendLine("        mavenCentral()")
            appendLine("        google()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("dependencyResolutionManagement {")
            appendLine("    repositories {")
            appendLine("        mavenCentral()")
            appendLine("        google()")
            appendLine("    }")
            appendLine("}")
        })
    }

    private fun generateRootSettingsGradle(
        rootDir: File,
        projectName: String,
        modulePaths: Set<String>
    ) {
        rootDir.resolve("settings.gradle.kts").writeText(buildString {
            appendLine(IDE_ONLY_COMMENT.trimIndent())
            appendLine()
            appendLine("rootProject.name = \"$projectName\"")
            appendLine()
            appendLine("pluginManagement {")
            appendLine("    repositories {")
            appendLine("        gradlePluginPortal()")
            appendLine("        mavenCentral()")
            appendLine("        google()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("dependencyResolutionManagement {")
            appendLine("    repositories {")
            appendLine("        mavenCentral()")
            appendLine("        google()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            for (path in modulePaths.sorted()) {
                appendLine("include(\":${path.replace('/', ':')}\")")
            }
        })
    }

    private fun generateRootBuildGradle(rootDir: File) {
        rootDir.resolve("build.gradle.kts").writeText(buildString {
            appendLine(IDE_ONLY_COMMENT.trimIndent())
            appendLine()
            appendLine("plugins {")
            appendLine("    kotlin(\"multiplatform\") version \"$KOTLIN_VERSION\" apply false")
            appendLine("}")
        })
    }

    private fun generateBuildGradle(config: KmpProjectConfig, outputDir: File) {
        outputDir.mkdirs()
        outputDir.resolve("build.gradle.kts").writeText(buildString {
            appendLine(IDE_ONLY_COMMENT.trimIndent())
            appendLine()

            // Plugins
            appendLine("plugins {")
            appendLine("    kotlin(\"multiplatform\") version \"$KOTLIN_VERSION\"")
            appendLine("}")
            appendLine()

            // Group and version
            appendLine("group = \"${config.projectIdentifier?.group ?: "com.example"}\"")
            appendLine("version = \"${config.projectIdentifier?.version?.toString() ?: "1.0.0"}\"")
            appendLine()

            // Kotlin multiplatform block
            appendLine("kotlin {")

            // Targets
            for (target in config.targets.sortedBy { it.name }) {
                appendLine(targetDeclaration(target))
            }
            appendLine()

            // Source sets
            appendLine("    sourceSets {")

            // Common source sets
            appendLine("        commonMain {")
            appendLine("            dependencies {")
            for (dep in config.commonDependencies) {
                appendLine("                api(\"${dep.groupId}:${dep.artifactId}:${dep.version}\")")
            }
            appendLine("            }")
            appendLine("        }")
            appendLine("        commonTest {")
            appendLine("            dependencies {")
            appendLine("                implementation(kotlin(\"test\"))")
            appendLine("            }")
            appendLine("        }")

            // Target-specific source sets with dependencies
            for ((target, deps) in config.targetDependencies) {
                if (deps.isNotEmpty()) {
                    val sourceSetName = target.sourceSetName
                    appendLine("        $sourceSetName {")
                    appendLine("            dependencies {")
                    for (dep in deps) {
                        val scope = when (dep.scope) {
                            DependencyScope.Test -> "implementation"
                            DependencyScope.Provided -> "compileOnly"
                            else -> "implementation"
                        }
                        appendLine("                $scope(\"${dep.groupId}:${dep.artifactId}:${dep.version}\")")
                    }
                    appendLine("            }")
                    appendLine("        }")
                }
            }

            appendLine("    }")
            appendLine("}")
        })
    }

    private fun targetDeclaration(target: KmpTarget): String {
        return when (target) {
            KmpTarget.Jvm -> "    jvm()"
            KmpTarget.Js, KmpTarget.Js.Browser, KmpTarget.Js.Node -> "    js(IR) { browser(); nodejs() }"
            KmpTarget.Wasm.Js -> "    wasmJs { browser() }"
            KmpTarget.Wasm.Wasi -> "    wasmWasi()"
            is KmpTarget.Wasm -> "    // Unknown wasm target: ${target.name}"
            KmpTarget.Native.MacosX64 -> "    macosX64()"
            KmpTarget.Native.MacosArm64 -> "    macosArm64()"
            KmpTarget.Native.IosArm64 -> "    iosArm64()"
            KmpTarget.Native.IosSimulatorArm64 -> "    iosSimulatorArm64()"
            KmpTarget.Native.IosX64 -> "    iosX64()"
            KmpTarget.Native.WatchosArm64 -> "    watchosArm64()"
            KmpTarget.Native.WatchosSimulatorArm64 -> "    watchosSimulatorArm64()"
            KmpTarget.Native.TvosArm64 -> "    tvosArm64()"
            KmpTarget.Native.TvosSimulatorArm64 -> "    tvosSimulatorArm64()"
            KmpTarget.Native.LinuxX64 -> "    linuxX64()"
            KmpTarget.Native.LinuxArm64 -> "    linuxArm64()"
            KmpTarget.Native.MingwX64 -> "    mingwX64()"
            KmpTarget.Native.AndroidNativeArm64 -> "    androidNativeArm64()"
            KmpTarget.Native.AndroidNativeArm32 -> "    androidNativeArm32()"
            KmpTarget.Native.AndroidNativeX64 -> "    androidNativeX64()"
            KmpTarget.Native.AndroidNativeX86 -> "    androidNativeX86()"
        }
    }

    private fun generateGradleProperties(outputDir: File) {
        outputDir.resolve("gradle.properties").writeText(buildString {
            appendLine("# IDE-only Gradle properties")
            appendLine("kotlin.code.style=official")
            appendLine("kotlin.mpp.stability.nowarn=true")
            appendLine("kotlin.native.ignoreDisabledTargets=true")
            appendLine()
            appendLine("# Disable actual Gradle build tasks since KBuild is used for building")
            appendLine("org.gradle.configureondemand=true")
        })
    }

    private fun generateGradleWrapper(outputDir: File) {
        // Create minimal wrapper properties so IntelliJ can sync
        val wrapperDir = outputDir.resolve("gradle/wrapper")
        wrapperDir.mkdirs()

        wrapperDir.resolve("gradle-wrapper.properties").writeText(buildString {
            appendLine("distributionBase=GRADLE_USER_HOME")
            appendLine("distributionPath=wrapper/dists")
            appendLine("distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10-bin.zip")
            appendLine("networkTimeout=10000")
            appendLine("validateDistributionUrl=true")
            appendLine("zipStoreBase=GRADLE_USER_HOME")
            appendLine("zipStorePath=wrapper/dists")
        })
    }

    // Extension to get project identifier from config
    private val KmpProjectConfig.projectIdentifier: com.ivieleague.kbuild.common.ProjectIdentifier?
        get() = null  // KmpProjectConfig doesn't have this yet, could be added
}

/**
 * Extension function to generate IDE Gradle files from a KmpProjectConfig.
 */
fun KmpProjectConfig.generateIdeGradle(outputDir: File = projectRoot): File {
    return GradleIdeBuild.generate(this, outputDir)
}
